# Generated by Django 6.1 on 2026-09-24 06:53

import django.core.validators
import django.db.models.deletion
import resumes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='title')),
                ('file', models.FileField(help_text='PDF resume, stored under MEDIA_ROOT/resumes/<user id>/.', max_length=255, upload_to=resumes.models.resume_upload_path, verbose_name='file')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size (bytes)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='content type')),
                ('is_default', models.BooleanField(default=False, help_text='At most one default resume per account.', verbose_name='default resume')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='parse status')),
                ('parse_error', models.TextField(blank=True, verbose_name='parse error')),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='The ParsedResume returned by the engine, stored as JSON.', verbose_name='parsed data')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='parsed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='job title')),
                ('job_description', models.TextField(verbose_name='job description')),
                ('score', models.FloatField(help_text='0-100, produced by the ATS scorer.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score')),
                ('keyword_coverage', models.FloatField(default=0.0, help_text='Fraction of the job description keywords found in the resume.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='keyword coverage')),
                ('matched_skills', models.JSONField(blank=True, default=list, verbose_name='matched skills')),
                ('missing_skills', models.JSONField(blank=True, default=list, verbose_name='missing skills')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='suggestions')),
                ('engine_version', models.CharField(blank=True, max_length=50, verbose_name='engine version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='resumes.resume', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'ATS analysis',
                'verbose_name_plural': 'ATS analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', '-created_at'], name='resumes_res_user_id_6019d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_resume_per_user'),
        ),
        migrations.AddIndex(
            model_name='atsanalysis',
            index=models.Index(fields=['resume', '-created_at'], name='resumes_ats_resume__b87b73_idx'),
        ),
    ]
