# Generated by Django 6.1 on 2026-10-01 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=8)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveSmallIntegerField(default=1)),
                ('raw_text', models.TextField()),
                ('parsed_data', models.JSONField(default=dict)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('general', 'General resume ATS check'), ('job', 'Job-specific analysis')], max_length=10)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('ats_score', models.PositiveSmallIntegerField()),
                ('job_match_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyzer.analyzedresume')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resume', '-created_at'], name='analyzer_an_resume__8ac0ef_idx')],
            },
        ),
    ]
