# Generated by Django 6.1 on 2026-10-08 07:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='location')),
                ('job_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20, verbose_name='job type')),
                ('salary_range', models.CharField(blank=True, help_text="Free-form, e.g. 'INR 12-18 LPA'.", max_length=50, verbose_name='salary range')),
                ('description', models.TextField(verbose_name='description')),
                ('requirements', models.TextField(help_text='The pasted job description; doubles as the text the ATS scorer matches candidate resumes against.', verbose_name='requirements')),
                ('is_active', models.BooleanField(default=True, help_text='Closed (inactive) jobs stop accepting applications.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(blank=True, help_text="Stamped from the recruiter's profile on creation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.company', verbose_name='company')),
                ('created_by', models.ForeignKey(help_text='Recruiter who published the job.', on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20, verbose_name='status')),
                ('message', models.TextField(blank=True, help_text='Optional cover note from the seeker.', verbose_name='message')),
                ('ats_score', models.FloatField(blank=True, help_text="Snapshot of the engine score for this resume against the job's requirements (0-100).", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ATS score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ats_analysis', models.ForeignKey(blank=True, help_text='The full scoring run behind ``ats_score``.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.atsanalysis', verbose_name='ATS analysis')),
                ('resume', models.ForeignKey(help_text='The parsed resume the applicant submitted.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='resumes.resume', verbose_name='resume')),
                ('seeker', models.ForeignKey(help_text='Denormalised copy of ``resume.user`` (always the caller).', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='job')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', '-created_at'], name='jobs_job_is_acti_5b4a60_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_by', '-created_at'], name='jobs_job_created_d1be9f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['seeker', '-created_at'], name='jobs_applic_seeker__7d04d3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', '-ats_score'], name='jobs_applic_job_id_ceb5c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'resume'), name='unique_application_per_job_resume'),
        ),
    ]
